john/urls.py
from django.urls import path
from . import views




urlpatterns = [
    path('', views.index, name='index'),
    path('tour/', views.tour, name='tour'),
    
]

portfolio/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('john.urls')),
    
    path("", include("allauth.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

john/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# HOME SECTION

class Home(models.Model):
    name = models.CharField(max_length=20)
    greetings_1 = models.CharField(max_length=50)
    
    picture = models.ImageField(upload_to='picture/')
    # save time when modified
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


# ABOUT SECTION

class About(models.Model):
    heading = models.CharField(max_length=50)
    career = models.CharField(max_length=20)
    description = models.TextField(blank=False)
    profile_img = models.ImageField(upload_to='profile/')
    
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.career


class Profile(models.Model):
    about = models.ForeignKey(About,
                                on_delete=models.CASCADE)
    social_name = models.CharField(max_length=10)
    link = models.URLField(max_length=200)



# SKILLS SECTION

class Category(models.Model):
    name = models.CharField(max_length=20)

    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    def __str__(self):
        return self.name

class Skills(models.Model):
    category = models.ForeignKey(Category,
                                on_delete=models.CASCADE)
    skill_name = models.CharField(max_length=20)

    

# PORTFOLIO SECTION

class Portfolio(models.Model):
    title = models.CharField(default="Video Title", max_length=50)
    image = models.ImageField(upload_to='portfolio/')
    link = models.URLField(max_length=200)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Portfolio {self.id}'

# STREAMER SECTION

class Streamers(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='portfolio/')
    link = models.URLField(max_length=200)

    def __str__(self):
        return self.name


# Tournament section

class Tourn(models.Model):
    tp = models.CharField(max_length=100, default='Tournament / Scrim')
    host = models.CharField(max_length=50)
    macth = models.CharField(max_length=20)
    details = models.TextField(blank=False)
    
    room = models.CharField(max_length=500, null=True, blank=True)

    when = models.DateTimeField(null=True)

    updated = models.DateTimeField(auto_now=True)
    

  

    def __str__(self):
        return self.host


class Results(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    gametype = models.CharField(max_length=2, default="MP/BR")
    game = models.ForeignKey(Tourn, on_delete=models.CASCADE)
    result = models.CharField(max_length=100, default="WIN 5-0")
    when = models.DateField(null=True)

    def __str__(self):
        return self.result


class Store(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='store/')
    link = models.URLField(max_length=200)
    price = models.IntegerField(max_length=100)

    def __str__(self):
        return self.name


class Tournament(models.Model):
    tp = models.CharField(max_length=100, default='Tournament / Scrim')
    host = models.CharField(max_length=200)
    when = models.DateTimeField()
    info = models.TextField()
    game_type = models.CharField(max_length=2, default="MP/BR")
    room = models.CharField(max_length=500, null=True, blank=True)
    result = models.CharField(max_length=500, null=True, blank=True)
    
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Participant'
        verbose_name_plural = 'Participants'

    def __str__(self):
        return self.tp

    


class Participants(models.Model):
    tournament = models.ForeignKey(Tournament,
                                   on_delete=models.CASCADE)
    team_name = models.CharField(max_length=20)


class News(models.Model):
    topic = models.CharField(max_length=50)
    content = models.TextField(blank=False)
    img = models.ImageField(upload_to='news/')

    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.topic


# TEAM SECTION

class Team(models.Model):
    player = models.CharField(default="Videos Title", max_length=55)
    image = models.ImageField(upload_to='portfolio/')

    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.player


class Livestream(models.Model):
    title = models.CharField(max_length=300)
    link = models.URLField(max_length=200)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    

john/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Home, Results, Store, Streamers, About, Profile, Category, Skills, Portfolio, Tourn, Tournament, Team, News, Livestream
from django.urls import reverse
from django.views.generic import DetailView, CreateView

def index(request):

    # Home
    home = Home.objects.latest('updated')

    # About
    about = About.objects.latest('updated')
    profiles = Profile.objects.filter(about=about)
    livestream = Livestream.objects.all()
    news = News.objects.order_by('updated')


    # Skills
    categories = Category.objects.order_by('-updated')

    # Portfolio
    portfolios = Portfolio.objects.order_by('-updated')
    # Streamers
    streamers = Streamers.objects.all()

    context = {
        'home': home,
        'about': about,
        'profiles': profiles,
        'categories': categories,
        'portfolios': portfolios,
        'streamers': streamers,
        'livestream': livestream,
        'news': news,
        
    }
    


    return render(request, 'index.html', context)


def tour(request):

    results = Results.objects.order_by('-name')
    team = Team.objects.order_by('-updated')

    home = Home.objects.latest('updated')
    tournament = Tournament.objects.order_by('-updated')
    tourn = Tourn.objects.order_by('-host')
    store = Store.objects.order_by('name')


    context = {
        'home': home,
        'store': store,
        'tournament': tournament,
        'team': team,

        'tourn': tourn,
        'results': results,

    }

    return render(request, 'tour.html', context)

john/templates/tour.html
{% extends 'account/base.html' %}
{% load static %}

{% block content %}
<!--===== HOME =====-->
            <section class="home" id="home">
                <div class="home__container bd-grid text text-center">
                    <h1 class="home__title"><span>{{ home.greetings_1|upper }}</span><br></h1>


                    <div class="home__scroll" style="z-index:10;">
                    {% if user.is_active  %}
                        <a href="#tour" class="home__scroll-link text text-left"><i class='bx bx-up-arrow-circle bx-fade-up' ></i></a>
                    {% else %}
                        <a href="#tour" class="home__scroll-link text text-left"><i class='bx bx-up-arrow-circle bx-fade-up' ></i></a>
                    {% endif %}
                    </div>
                    {% if user.is_active %}
                    <br>
                    <br>
                    <p class="about__text" style=" color: white; z-index:10; text-align:center;font-family:'Monsterat';text-shadow: 0 3px 2px var(--dark-color);">&nbsp;{{ user.username }}<br>Tournaments</p>
                    {% else %}
                    <p class="about__text" style=" color: white; z-index:10; text-align:center;font-family:'Monsterat'; text-shadow: 0 3px 2px var(--dark-color);">Tournaments</p>

                    {% endif %}

                    <img src="{{ home.picture.url }}" alt="" class="home__img">
                </div>
            </section>
                <script src="https://apps.elfsight.com/p/platform.js" defer></script>
            <div class="elfsight-app-fe535110-2fb0-4d22-91ba-1af24c9b2f00"></div>

               <!--Tournaments-->

            <section class="about container bd-grid" id="tour">
                <h1 class="section-title">BloodLine Tournaments</h1>
                <small><p style='text-align:center;border:1px solid black;padding:10px;'>This is a temporary display for Tournaments. A more detailed Tournament section for Bloodline is currently in development <i style="color:brown;" class="bx bx-cog bx-spin"></i></p></small><br>
                <small><p style='text-align:center;'><i>Note that each room ID will be available 10 - 30min before starting time.</i></p></small><br>
                {% for t in tournament %}






                <div class="skills__container " style="color:white;text-align:center;border:1px solid white;border-radius: 5px; box-shadow:1px 1px 5px 1px black; padding:10px;background-image: linear-gradient(to bottom, var(--dark-color), black, black, black, black, black, var(--dark-color));">


                <h2 style="text-align:center;" class="about__profession">{{t.tp|upper}}</h2>
                    <div class="skills__img" style="display: block;
  margin-left: auto;
  margin-right: auto;height:auto;
  width: 50%;border:1px solid white;border-radius: 8px;padding:3px;">
                        <img src="{% static 'assets/img/m.png' %}" alt="">
                    </div>
                    <br>
                    <div style="text-align:center;">

                        <h2 class="about__profession"><b>Host:&nbsp;</b> {{ t.host|upper }}</h2>
                        <span class="about__profession"><b style="text-align:left;">Game Type:&nbsp;</b> {{ t.game_type }}</span>
                        <p class="about__text"><b>Details:&nbsp;</b> {{ t.info }}</p>
                        <p class="about__text"><b>When:&nbsp;</b> {{ t.when }}</p>

                        <a href="#" class="bx-flashing about__text text-light " ><i class="bx bxl-discord text-dark"></i>Register Here!</a>
                        <h2 class="about__profession">Registered Teams :</h2>



                            <form placeholder="All Teams" >
                            <i class='bx bx-group bx-md' ></i><br>
                              <label></label>
                              <select class="btn btn-danger btn-outline-dark text-light" style="transition: 1s; justify-content:center; left:10px;">
                              <option value="" disabled selected>All Teams</option>

                              {% for skills in t.participants_set.all %}
                                <option style="text-align:center; color:white;" value="All"  disabled="disabled"><i class='bx bx-group' ></i> {{ skills.team_name}}</option>

                                {% endfor %}

                              </select>
                              <br><br>

                            </form>

                        <div class="fb-share-button text text-center" data-href="https://thebloodline.pythonanywhere.com/tour/#tour" data-layout="button" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fthebloodline.pythonanywhere.com%2Ftour%2F%23tour&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>

                    </div>

                </div>
                <br>
            {% endfor %}

            </section>

            <!--Results-->
            <section class="about section" id="results">
                <h2 class="section-title">Results</h2>
                <small><p style="text-align:center;"><i>Some of BloodLine's recent Results</i></p></small><br>

                <head>
                    <style>
                    table {
                    border-radius:3px;
                    border-collapse: collapse;
                    width: 100%;
                    color:white;
                    background-color: var(--first-color)
                    }

                    td, th {
                    border: 1px solid white;
                    border-radius: 5px;
                    text-align: center;
                    padding: 8px;
                    }

                    tr:nth-child(even) {
                    background-color: var(--dark-color);
                    color: white;
                    }
                    </style>
                </head>

                    <div class="about__text" style="justify-content:center; text-align:center;">

                        <table>
                            <tr>
                                <th><b>Host</b></th>
                                <th><b>Date</b></th>
                                <th><b>Game Type</b></th>
                                <th><b>Result</b></th>
                            </tr>



                           <tr>


                            {%for r in tournament %}
                                
                                <td>{{ r.host }}</td>
                                

                                <td>{{ r.when }}</td>
                                <td>{{ r.game_type }}</td>

                                <td>{{ r.result }}</td>




                            </tr>
                            {% endfor %}






                        </table>






                </div>
            </section>

            <!--===== PORTFOLIO =====-->
            <section class="portfolio section" id="team">
                <h2 class="section-title" style="color:white;">BloodLine Alpha Squad</h2>
                <p class="about__text text text-muted" style='text-align:center;'><small>Click To View Player</small></p>











                <div class="portfolio__container bd-grid">

                    {% for t in team %}


                    <div class="portfolio__img" style="width:250px;">
                        <img src="{{ t.image.url }}" alt="">

                        <div class="portfolio__link">
                            <p><a href="{{ t.image.url }}" target='_blank' class="portfolio__link-name" style='color:white; text-decoration:none;'><i style='color:white;' class="bx bx-user bx-flashing"></i> View</a></p>
                        </div>
                        <h2 class="about__text" style='text-align:center;'>{{t.player}}</h2>

                    </div>



                    {% endfor %}


                </div>

            </section>





        <!--===== FOOTER =====-->
        <footer class="footer section" id='footer'>
            <div class="footer__container bd-grid" style='text-align:center;'>
                <div class="footer__data">
                    <h2 class="footer__title">BLOODLINE :</h2>
                    <p class="footer__text" style='color:white;'>STAY TUNED...</p>
                </div>



                <div class="footer__data">
                    <h2 class="footer__title">FOLLOW US</h2>
                    <a href="#" class="footer__social"><i class='bx bxl-facebook' ></i></a>
                    <a href="#" class="footer__social"><i class='bx bxl-discord' ></i></a>
                    <a href="#" class="footer__social"><i class='bx bxl-twitch' ></i></a>
                </div>




            </div>
        </footer>




{% endblock content %}